#!/bin/bash

make clean;
make bfs2 SERIAL=0 ENABLE_PICKLEDEVICE=1 ENABLE_GEM5=1;
make cc2 SERIAL=0 ENABLE_PICKLEDEVICE=1 ENABLE_GEM5=1;
make pr2 SERIAL=0 ENABLE_PICKLEDEVICE=1 ENABLE_GEM5=1;
make tc2 SERIAL=0 ENABLE_PICKLEDEVICE=1 ENABLE_GEM5=1;
make bc2 SERIAL=0 ENABLE_PICKLEDEVICE=1 ENABLE_GEM5=1;
make sssp2 SERIAL=0 ENABLE_PICKLEDEVICE=1 ENABLE_GEM5=1;
